
apiVersion: v1  
kind: Namespace  
metadata:  
   name: nginx-app
   labels:  
     name: nginxs 

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mynignx2
spec:
  replicas: 1
  selector:
    name: nginx2
  template:
    metadata:
       labels:
         name: nginx2
    spec:
        containers:
        - name: nginx2
          image: nginx
          ports:
          - containerPort: 80
          readinessProbe:
            tcpSocket:
               port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: git-volume2
        volumes:
            - name: git-volume2
              persistentVolumeClaim:
                claimName: myclaim2
---

apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  selector:
    name: nginx2
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: 31605
  type: NodePort
