kind: PersistentVolume
apiVersion: v1
metadata:
  name: mydemo-pv
  labels:
    type: local-dalong
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/dalong/pvapp"